# Generated by Django 5.2.8 on 2025-12-02 23:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_booking'),
        ('users', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('bmi', models.FloatField(blank=True, editable=False, null=True)),
                ('bmi_category', models.CharField(blank=True, editable=False, max_length=20)),
                ('primary_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance Improvement'), ('strength', 'Strength Building'), ('flexibility', 'Flexibility'), ('rehabilitation', 'Rehabilitation'), ('general_fitness', 'General Fitness'), ('sports_performance', 'Sports Performance')], default='general_fitness', max_length=50)),
                ('activity_level', models.CharField(choices=[('light', 'Light (exercise 1-3 days/week)'), ('moderate', 'Moderate (exercise 3-5 days/week)'), ('active', 'Active (exercise 6-7 days/week)'), ('very_active', 'Very Active (hard exercise 6-7 days/week)')], default='moderate', max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (< 6 months)'), ('intermediate', 'Intermediate (6 months - 2 years)'), ('advanced', 'Advanced (> 2 years)')], default='beginner', max_length=20)),
                ('months_experience', models.PositiveIntegerField(default=0)),
                ('preferred_times', models.JSONField(default=list, help_text="Preferred workout times (e.g., ['morning', 'evening'])")),
                ('has_injuries', models.BooleanField(default=False)),
                ('injuries_description', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('home_equipment', models.JSONField(default=list, help_text='List of equipment available at home')),
                ('preferred_duration_min', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)])),
                ('days_per_week', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('preferences_history', models.JSONField(default=list, help_text='Historical preferences and adjustments')),
                ('llm_prompt_context', models.TextField(blank=True, help_text='Cached prompt context for LLM')),
                ('last_workout_date', models.DateField(blank=True, null=True)),
                ('workout_streak', models.PositiveIntegerField(default=0)),
                ('total_workouts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_llm_update', models.DateTimeField(blank=True, null=True)),
                ('preferred_class_types', models.ManyToManyField(blank=True, related_name='user_preferences', to='classes.classtype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitness Profile',
                'verbose_name_plural': 'Fitness Profiles',
                'db_table': 'fitness_profiles',
            },
        ),
    ]
