# Generated by Django 5.2.8 on 2025-11-27 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='instructor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='classes',
                to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='level',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='classes',
                to='classes.level'),
        ),
        migrations.AddIndex(
            model_name='fitnessclass',
            index=models.Index(fields=['start_time', 'is_active'],
                               name='fitness_cla_start_t_8cee2e_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessclass',
            index=models.Index(fields=['class_type', 'level'],
                               name='fitness_cla_class_t_38b57a_idx'),
        ),
    ]
