# Generated by Django 5.2.8 on 2025-11-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='name',
        ),
    ]
