# Generated by Django 5.2.8 on 2025-11-28 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_fitnessclass_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.fitnessclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booked_at'],
                'indexes': [models.Index(fields=['status', 'fitness_class'], name='bookings_status_cd9ea9_idx'), models.Index(fields=['user', 'booked_at'], name='bookings_user_id_0aa9cb_idx')],
                'unique_together': {('user', 'fitness_class')},
            },
        ),
    ]
